"""crear tabla boxes

Revision ID: 07e09c43f708
Revises: 74542f60752a
Create Date: 2025-12-30 20:21:43.205121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07e09c43f708'
down_revision: Union[str, Sequence[str], None] = '74542f60752a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('base_balance', sa.Float(), nullable=True),
    sa.Column('insurance_balance', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_boxes_id'), 'boxes', ['id'], unique=False)
    op.create_table('box_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('movement_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_insurance', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('performed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_box_movements_id'), 'box_movements', ['id'], unique=False)
    op.drop_index('ix_topes_prestamo_cobrador_id', table_name='topes_prestamo')
    op.drop_index('ix_topes_prestamo_id', table_name='topes_prestamo')
    op.drop_index('ix_topes_prestamo_supervisor_id', table_name='topes_prestamo')
    op.drop_table('topes_prestamo')
    op.drop_index('ix_caja_movimientos_caja_id', table_name='caja_movimientos')
    op.drop_index('ix_caja_movimientos_id', table_name='caja_movimientos')
    op.drop_table('caja_movimientos')
    op.drop_index('ix_cajas_id', table_name='cajas')
    op.drop_index('ix_cajas_user_id', table_name='cajas')
    op.drop_table('cajas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cajas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('cajas_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo', postgresql.ENUM('PRINCIPAL', 'MICROSEGURO', name='cajatipo'), autoincrement=False, nullable=True),
    sa.Column('saldo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='cajas_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cajas_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_cajas_user_id', 'cajas', ['user_id'], unique=False)
    op.create_index('ix_cajas_id', 'cajas', ['id'], unique=False)
    op.create_table('caja_movimientos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('caja_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo', postgresql.ENUM('INGRESO', 'EGRESO', 'TRANSFERENCIA', 'RETIRO', 'GASTO', 'MICROSEGURO', 'PRESTAMO', 'ABONO', 'VOLADO', 'CIERRE', name='movimientotipo'), autoincrement=False, nullable=True),
    sa.Column('monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('usuario_origen_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usuario_destino_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('credito_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['caja_id'], ['cajas.id'], name='caja_movimientos_caja_id_fkey'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], name='caja_movimientos_cliente_id_fkey'),
    sa.ForeignKeyConstraint(['credito_id'], ['credits.id'], name='caja_movimientos_credito_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_destino_id'], ['users.id'], name='caja_movimientos_usuario_destino_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_origen_id'], ['users.id'], name='caja_movimientos_usuario_origen_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='caja_movimientos_pkey')
    )
    op.create_index('ix_caja_movimientos_id', 'caja_movimientos', ['id'], unique=False)
    op.create_index('ix_caja_movimientos_caja_id', 'caja_movimientos', ['caja_id'], unique=False)
    op.create_table('topes_prestamo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supervisor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cobrador_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('monto_maximo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cobrador_id'], ['users.id'], name='topes_prestamo_cobrador_id_fkey'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], name='topes_prestamo_supervisor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='topes_prestamo_pkey')
    )
    op.create_index('ix_topes_prestamo_supervisor_id', 'topes_prestamo', ['supervisor_id'], unique=False)
    op.create_index('ix_topes_prestamo_id', 'topes_prestamo', ['id'], unique=False)
    op.create_index('ix_topes_prestamo_cobrador_id', 'topes_prestamo', ['cobrador_id'], unique=False)
    op.drop_index(op.f('ix_box_movements_id'), table_name='box_movements')
    op.drop_table('box_movements')
    op.drop_index(op.f('ix_boxes_id'), table_name='boxes')
    op.drop_table('boxes')
    # ### end Alembic commands ###
