"""modulo caja, microseguro, volados, topes, movimientos

Revision ID: 6884c44af594
Revises: 5133de32ba29
Create Date: 2025-12-30 17:46:41.653573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6884c44af594'
down_revision: Union[str, Sequence[str], None] = '5133de32ba29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cajas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('PRINCIPAL', 'MICROSEGURO', name='cajatipo'), nullable=True),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cajas_id'), 'cajas', ['id'], unique=False)
    op.create_index(op.f('ix_cajas_user_id'), 'cajas', ['user_id'], unique=False)
    op.create_table('topes_prestamo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('cobrador_id', sa.Integer(), nullable=True),
    sa.Column('monto_maximo', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cobrador_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topes_prestamo_cobrador_id'), 'topes_prestamo', ['cobrador_id'], unique=False)
    op.create_index(op.f('ix_topes_prestamo_id'), 'topes_prestamo', ['id'], unique=False)
    op.create_index(op.f('ix_topes_prestamo_supervisor_id'), 'topes_prestamo', ['supervisor_id'], unique=False)
    op.create_table('caja_movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caja_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('INGRESO', 'EGRESO', 'TRANSFERENCIA', 'RETIRO', 'GASTO', 'MICROSEGURO', 'PRESTAMO', 'ABONO', 'VOLADO', 'CIERRE', name='movimientotipo'), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('usuario_origen_id', sa.Integer(), nullable=True),
    sa.Column('usuario_destino_id', sa.Integer(), nullable=True),
    sa.Column('credito_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caja_id'], ['cajas.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['credito_id'], ['credits.id'], ),
    sa.ForeignKeyConstraint(['usuario_destino_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['usuario_origen_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caja_movimientos_caja_id'), 'caja_movimientos', ['caja_id'], unique=False)
    op.create_index(op.f('ix_caja_movimientos_id'), 'caja_movimientos', ['id'], unique=False)
    op.drop_index('ix_items_id', table_name='items')
    op.drop_index('ix_items_title', table_name='items')
    op.drop_table('items')
    op.add_column('clients', sa.Column('estado', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'estado')
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    op.create_index('ix_items_title', 'items', ['title'], unique=False)
    op.create_index('ix_items_id', 'items', ['id'], unique=False)
    op.drop_index(op.f('ix_caja_movimientos_id'), table_name='caja_movimientos')
    op.drop_index(op.f('ix_caja_movimientos_caja_id'), table_name='caja_movimientos')
    op.drop_table('caja_movimientos')
    op.drop_index(op.f('ix_topes_prestamo_supervisor_id'), table_name='topes_prestamo')
    op.drop_index(op.f('ix_topes_prestamo_id'), table_name='topes_prestamo')
    op.drop_index(op.f('ix_topes_prestamo_cobrador_id'), table_name='topes_prestamo')
    op.drop_table('topes_prestamo')
    op.drop_index(op.f('ix_cajas_user_id'), table_name='cajas')
    op.drop_index(op.f('ix_cajas_id'), table_name='cajas')
    op.drop_table('cajas')
    # ### end Alembic commands ###
