"""actualizacion caja usuarios clientes

Revision ID: 74542f60752a
Revises: 6884c44af594
Create Date: 2025-12-30 19:50:16.264853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74542f60752a'
down_revision: Union[str, Sequence[str], None] = '6884c44af594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
